// <auto-generated />
using System;
using Characters.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Characters.Migrations
{
    [DbContext(typeof(CharactersDbContext))]
    partial class CharactersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("characters")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Characters.Entities.Attack", b =>
                {
                    b.Property<Guid>("AttackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attack_id");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("integer")
                        .HasColumnName("attack_bonus");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("damage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("AttackId");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_attacks", "characters");
                });

            modelBuilder.Entity("Characters.Entities.Character", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("additional_notes");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Alignment")
                        .HasColumnType("text")
                        .HasColumnName("alignment");

                    b.Property<string>("AlliesAndOrganizations")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("allies_and_organizations");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer")
                        .HasColumnName("armor_class");

                    b.Property<string>("Background")
                        .HasColumnType("text")
                        .HasColumnName("background");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("backstory");

                    b.Property<string>("Bonds")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("bonds");

                    b.Property<string>("CharacterTraits")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("character_traits");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer")
                        .HasColumnName("charisma");

                    b.Property<string>("Class")
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer")
                        .HasColumnName("constitution");

                    b.Property<int>("CopperPieces")
                        .HasColumnType("integer")
                        .HasColumnName("copper_pieces");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<int>("DeathSaveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("death_save_failures");

                    b.Property<int>("DeathSaveSuccesses")
                        .HasColumnType("integer")
                        .HasColumnName("death_save_successes");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer")
                        .HasColumnName("dexterity");

                    b.Property<string>("DistinguishingMarks")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("distinguishing_marks");

                    b.Property<int>("ElectrumPieces")
                        .HasColumnType("integer")
                        .HasColumnName("electrum_pieces");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("equipment");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer")
                        .HasColumnName("experience_points");

                    b.Property<string>("Eyes")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("eyes");

                    b.Property<string>("FeaturesAndTraits")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("features_and_traits");

                    b.Property<string>("Flaws")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("flaws");

                    b.Property<int>("GoldPieces")
                        .HasColumnType("integer")
                        .HasColumnName("gold_pieces");

                    b.Property<string>("Hair")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("hair");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("HitDiceRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("hit_dice_remaining");

                    b.Property<string>("HitDieType")
                        .HasColumnType("text")
                        .HasColumnName("hit_die_type");

                    b.Property<string>("Ideals")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("ideals");

                    b.Property<int>("InitiativeBonus")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_bonus");

                    b.Property<bool>("Inspiration")
                        .HasColumnType("boolean")
                        .HasColumnName("inspiration");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("OtherProficiencies")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("other_proficiencies");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("PlatinumPieces")
                        .HasColumnType("integer")
                        .HasColumnName("platinum_pieces");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("player_name");

                    b.Property<int>("PreparedLimit")
                        .HasColumnType("integer")
                        .HasColumnName("prepared_limit");

                    b.Property<string>("Race")
                        .HasColumnType("text")
                        .HasColumnName("race");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<int>("SilverPieces")
                        .HasColumnType("integer")
                        .HasColumnName("silver_pieces");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("skin");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int>("SpellSlotsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("spell_slots_total");

                    b.Property<int>("SpellSlotsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("spell_slots_used");

                    b.Property<string>("SpellcastingClass")
                        .HasColumnType("text")
                        .HasColumnName("spellcasting_class");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<int>("TempHp")
                        .HasColumnType("integer")
                        .HasColumnName("temp_hp");

                    b.Property<string>("Treasure")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("treasure");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer")
                        .HasColumnName("wisdom");

                    b.HasKey("CharacterId");

                    b.HasIndex("RoomId");

                    b.ToTable("characters", "characters");
                });

            modelBuilder.Entity("Characters.Entities.SaveProficiency", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("Ability")
                        .HasColumnType("text")
                        .HasColumnName("ability");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.HasKey("CharacterId", "Ability");

                    b.ToTable("character_save_proficiencies", "characters");
                });

            modelBuilder.Entity("Characters.Entities.SkillProficiency", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("Skill")
                        .HasColumnType("text")
                        .HasColumnName("skill");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.HasKey("CharacterId", "Skill");

                    b.ToTable("character_skill_proficiencies", "characters");
                });

            modelBuilder.Entity("Characters.Entities.Spell", b =>
                {
                    b.Property<Guid>("SpellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("spell_id");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("casting_time");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("components");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("duration");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<bool>("Prepared")
                        .HasColumnType("boolean")
                        .HasColumnName("prepared");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("range");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("school");

                    b.HasKey("SpellId");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_spells", "characters");
                });

            modelBuilder.Entity("Characters.Entities.Attack", b =>
                {
                    b.HasOne("Characters.Entities.Character", null)
                        .WithMany("Attacks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Characters.Entities.SaveProficiency", b =>
                {
                    b.HasOne("Characters.Entities.Character", null)
                        .WithMany("SaveProficiencies")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Characters.Entities.SkillProficiency", b =>
                {
                    b.HasOne("Characters.Entities.Character", null)
                        .WithMany("SkillProficiencies")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Characters.Entities.Spell", b =>
                {
                    b.HasOne("Characters.Entities.Character", null)
                        .WithMany("Spells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Characters.Entities.Character", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("SaveProficiencies");

                    b.Navigation("SkillProficiencies");

                    b.Navigation("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
